development:
  adapter: postgresql
  encoding: unicode
  database: jobs_hunt
  pool: 5
  username:
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: veto_prod
#   pool: 5
#   username: deploy
#   password: veto@123